name: Update Mods

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Run update script
        run: |
          dotnet scripts/mods.cs update

      - name: Fix JSON formatting
        run: |
          dotnet scripts/mods.cs fix

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          COMMIT_MSG=$(cat update-log.txt || echo "Update mods")

          git add mods/ mods.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "$COMMIT_MSG"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi

      - name: Clean up update-log.txt
        run: rm -f update-log.txt
